# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- checkout: samiyaakhtar/solid-doodle
  persistCredentials: true
  clean: true

- powershell: |
   git --version
   git checkout master
   New-Item -Path "$(System.DefaultWorkingDirectory)" -Name "testfile.txt" -ItemType "file" -Value "This is a text string."
   Write-Host "new file created, now adding file to git"
   git add -A
   Write-Host "setup author info"
   git config user.email samiya@samiya.ca
   git config user.name "samiya bot"
   Write-Host "git commit with message"
   git commit -a -m "Test Commit from Azure DevOps"
   Write-Host "git push"
   git push
