# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

resources:         
  repositories:
  - repository: secondaryRepo
    type: github
    name: samiyaakhtar/solid-doodle
    endpoint: solid-doodle-push-auth

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- checkout: secondaryRepo  
  clean: false
  fetchDepth: 5
  lfs: true
  submodules: true
  persistCredentials: true

- script: |
   git --version
   #  git clone https://github.com/samiyaakhtar/solid-doodle.git
   cd solid-doodle
   git checkout master

   # Create dummy file
   echo "Creating file"
   DATE=$(date +"%Y%m%d%H%M")
   touch $DATE.log
   ls -a
   git add $DATE.log

   echo "new file created, now adding file to git"
   git add -A
   echo "setup author info"
   git config user.email samiya@samiya.ca
   git config user.name "samiya bot"
   echo "git commit with message"
   git commit -a -m "Test Commit from Azure DevOps"
   echo "git push"
   git push
