# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

# resources:         
#   repositories:
#   - repository: destinationRepo
#     type: git
#     name: epicstuff/samiya-test
#     endpoint: destination-repo-test

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- checkout: self
  persistCredentials: true
  clean: true

- powershell: |
   git --version
   git clone https://github.com/samiyaakhtar/solid-doodle.git
   cd solid-doodle
   git checkout master
   #  New-Item -Path "$(System.DefaultWorkingDirectory)" -Name "testfile.txt" -ItemType "file" -Value "This is a text string."
   
   #  echo "Creating file"
   #  $DATE=((Get-Date).ToString())
   #  echo $null >> $DATE.log
   #  #  touch $DATE.log
   #  ls -a
   #  git add $DATE.log

   Write-Host "new file created, now adding file to git"
   #  git add -A
   Write-Host "setup author info"
   git config user.email you@you.com
   git config user.name "your name"
   Write-Host "git commit with message"
   git commit --allow-empty -a -m "Test Commit from Azure DevOps"
   git remote set-url origin git@github.com:samiyaakhtar/solid-doodle.git
   Write-Host "git push"
   git push

# - checkout: destinationRepo  
#   clean: false
#   fetchDepth: 5
#   lfs: true
#   submodules: true
#   persistCredentials: true

# - script: |
#    git --version
#    git clone git@github.com:samiyaakhtar/solid-doodle.git
#    cd solid-doodle
#    git checkout master

#    # Create dummy file
#    echo "Creating file"
#    DATE=$(date +"%Y%m%d%H%M")
#    touch $DATE.log
#    ls -a
#    git add $DATE.log

#    echo "new file created, now adding file to git"
#    git add -A
#    echo "setup author info"
#    git config user.email samiya@samiya.ca
#    git config user.name "samiya bot"
#    echo "git commit with message"
#    git commit -a -m "Test Commit from Azure DevOps"
#    echo "git push"
#    git push 
