# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

resources:         
  repositories:
  - repository: destinationRepo
    type: github
    name: samiyaakhtar/solid-doodle
    endpoint: solid-doodle-push-auth

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
# - checkout: destinationRepo
#   persistCredentials: true
#   clean: true

- powershell: |
   git --version
   git clone https://github.com/samiyaakhtar/solid-doodle.git
   cd solid-doodle
   git checkout master
   Write-Host "setup author info"
   git config user.email "me@samiya.ca"
   git config user.name "azure-pipelines[bot]"
   Write-Host "git commit with message"
   git commit --allow-empty -a -m "Updating yaml files - Azure DevOps"
   git remote set-url origin git@github.com:samiyaakhtar/solid-doodle.git
   Write-Host "git push"
   git push https://$(accesstoken)@github.com/samiyaakhtar/solid-doodle.git
